permalink: /:year-:month-:day/:title
markdown: kramdown
exclude: ["README.md", "CNAME", "LICENSE", "build", "config.rb", "Gruntfile.js", "package.json", "jshint.json"]

title : "Fusion (with PHD Comics)"
id : "" # NA
description : "Short description" # changeme
thumb: "thumb.gif" # changem
version: "0.0.3"

ml_url: "https://minutelabs.io"
ml_library: "https://labs.minutelabs.io/library"
ml_assets: "https://labs.minutelabs.io/assets"
library_path: "library-build"

show :
  branding: true
  details: true
  comments: true
